# Site settings
title: Doedels Kindermode
description: v1.0
baseurl: ""
url: ""

keep_files: ['assets' ]
exclude: ['node_modules','package.json']

source: source/_html
destination: build

# Build settings
markdown: kramdown

plugins:
  - jekyll-tidy
